server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://host.docker.internal:5432/wallet_db'
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  kafka:
    consumer:
      bootstrap-servers: 'host.docker.internal:9092'
      group-id: wallet
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 'host.docker.internal:9092'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    com.challenge.wallet.client:
      UserClient: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: full